### PR TITLE
English Translated

### LINKED ISSUE #342: Translate this book in English
I would like an English translation for this awesome book.

### PR DESCRIPTION
**Pull request by Ayanrocks**
Fix #342 . Book translated to english. Although some code needs to be fixed and request for grammer check.

### CODE REVIEW

**Comment by chai2010** [comment]
感动 👍👍👍

**Comment by Delta456** [comment]
Thanks @Ayanrocks

**Comment by Delta456** [comment]
`func` instead of `Func` in all occurrences.

**Comment by Ayanrocks** [comment]
> `func` instead of `Func` in all occurrences.

yes that is something that needs to be fixed. I have fixed in many places but don't have time to fix them all. If anyone can do this would then it would be great. Beside code everything else is good. Still request you to check the grammars.

**Comment by Delta456** [comment]
I will PR the fixes when this RR will be merged.

**Comment by Ayanrocks** [comment]
> I will PR the fixes when this PR will be merged. Also did you translated by hand?

No its machine translated with google. Thus the errors and typos :P

**Comment by Delta456** [comment]
@Ayanrocks If you used Google Translate then that could be done by anyone even I could have because I wanted it but I didn't do it because there will be many mistakes in translating so I think its better for a native Chinese speaker to translate it into English.

**Comment by Ayanrocks** [comment]
> @Ayanrocks If you used Google Translate then that could be done by anyone even I could have because I wanted it but I didn't do it because there will be many mistakes in translating so I think its better for a native Chinese speaker to translate it into English.

The meaning or gist of the content is still remains same. Only have errors in grammars that can be fixed manually. You can start reading and report to places where it doesnt make any sense and we can fix it. At the end you need the knowledge of the book, and not the grammar.

**Comment by Delta456** [comment]
> > @Ayanrocks If you used Google Translate then that could be done by anyone even I could have because I wanted it but I didn't do it because there will be many mistakes in translating so I think its better for a native Chinese speaker to translate it into English.
> 
> The meaning or gist of the content is still remains same. Only have errors in grammars that can be fixed manually. You can start reading and report to places where it doesnt make any sense and we can fix it. At the end you need the knowledge of the book, and not the grammar.

Ok then 👍

**Comment by Delta456** [comment]
@Ayanrocks please fix the code errors.

**Pull request closed without merging**
